"""'Init'

Revision ID: 2ebb399c3d80
Revises: 1daa6c1e8fe7
Create Date: 2023-05-14 16:13:15.744383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebb399c3d80'
down_revision = '1daa6c1e8fe7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
